skill={
    mod:{
        targetEnabled:function(card,player,target){
            if(get.type(card)=='delay'){
                return false;
            }
        },
    },
    trigger:{
        player:["phaseZhunbeiBefore","phaseJieshuBefore"],
    },
    forced:true,
    audio:2,
    group:"yinhu_ys_2",
    content:function(){
        trigger.cancel();
        game.log(player,'跳过了',event.triggername=='phaseZhunbeiBefore'?'准备阶段':'结束阶段');
    },
    subSkill:{
        2:{
            popup:false,
            trigger:{
                player:"phaseJudgeBefore",
            },
            forced:true,
            content:function(){
                trigger.cancel();
                game.log(player,'跳过了判定阶段');
            },
        }
    }
}