skill={
    trigger:{
        source:"damageBefore",
    },
    forced:true,
    direct:true,
    filter:function(event,player){
        return event.player.hujia>0
    },
    content:function(){
        trigger.player.changeHujia(-trigger.player.hujia)
        trigger.player.draw(trigger.player.hujia)
    },
    group:['yinhu_sp_1','yinhu_sp_2'],
    subSkill:{
        1:{
            mod:{
                targetEnabled:function(card,player,target){
                    if(get.type(card)=='delay'){
                        return false;
                    }
                },
            },
            trigger:{
                player:["phaseZhunbeiBefore","phaseJieshuBefore"],
            },
            forced:true,
            content:function(){
                trigger.cancel();
                game.log(player,'跳过了',event.triggername=='phaseZhunbeiBefore'?'准备阶段':'结束阶段');
            },
        },
        2:{
            popup:false,
            trigger:{
                player:"phaseJudgeBefore",
            },
            forced:true,
            content:function(){
                trigger.cancel();
                game.log(player,'跳过了判定阶段');
            },
        }
    },
}