skill={
    trigger:{
        player:"phaseBegin"
    },
    direct:true,
    init:function(player){
        if(!player.storage.telina_th) player.storage.telina_th=0
    },
    mark:true,
    intro:{
        content:function(storage,player,skill){return '当前有'+storage+'个标记'}
    },
    content:function(){
        if(player.storage.telina_th>0){player.addTempSkill("qixi","phaseEnd")}
        if(player.storage.telina_th>1){player.addTempSkill("duanliang","phaseEnd")}
        if(player.storage.telina_th>2){player.addTempSkill("guose","phaseEnd")}
    },
    group:"telina_th_int",
    subSkill:{
        "int":{
            trigger:{
                player:"phaseAfter"
            },
            content:function(){
                player.storage.telina_th=0
                player.updateMark("telina_th")
            }
        }
    }
}