skill={
    trigger:{
        player:"damageAfter",
    },
    forced:true,
    usable:1,
    filter:function(event,player){
        return _status.currentPhase!=player;
    },
    content:function(){
        player.addTempSkill("milism_ql_1",['phaseAfter','phaseBefore']);
        player.addTempSkill("milism_ql_2",{player:"phaseBegin"})
    },
    subSkill:{
        "1":{
            forced:true,
            trigger:{
                player:"damageBegin1",
            },
            priority:15,
            mark:true,
            intro:{
                content:"你受到伤害前，免除之",
            },
            content:function(){
                trigger.cancel()
            },
            ai:{
                effect:{
                    target:function(card,player,target,current){if(get.type(card)=='trick'||card.name=='sha') return'zeroplayertarget';},
                },
            },
            sub:true,
        },
        "2":{
            trigger:{
                target:"useCardToBefore",
            },
            forced:true,
            priority:15,
            filter:function(event,player){
                return get.type(event.card)=='trick'&&event.card.name!='wugu'&&event.card.name!='taoyuan';
            },
            content:function(){
                game.log(player,'发动了潜鳞，',trigger.card,'对',trigger.target,'失效')
                trigger.cancel();
            },
            mod:{
                targetEnabled:function(card,player,target,now){
                    if(card.name=='bingliang'||card.name=='lebu') return false;
                },
            },
            mark:true,
            intro:{
                content:"除【五谷丰登】和【桃园结义】外，普通锦囊牌对你无效。且你不会成为【乐不思蜀】和【兵粮寸断】的目标。",
            },
            ai:{
                effect:{
                    target:function(card,player,target,current){
                        if(get.type(card)=='trick') return 'zeroplayertarget';
                    },
                },
            },
            sub:true,
        },
    },
}