skill={
    trigger:{
        player:"loseHpEnd"
    },
    filter:function(event,player){
        return event.num>=2
    },
    forced:true,
    content:function(){
        player.addTempSkill('tiers_kh_1',{player:"phaseBegin"})
        player.addTempSkill('tiers_kh_draw')
        player.addTempSkill('tiers_kh_use')
    },
    subSkill:{
        1:{
            trigger:{
                source:"damageEnd"
            },
            filter:function(event,player){
                return event.num>0&&event.player!=event.target
            },
            content:function(){
                player.recover()
            },
        },
        draw:{
            trigger:{
                global:"phaseAfter",
            },
            silent:true,
            forced:true,
            content:function (){
                player.phaseDraw();
            },
            sub:true,
            popup:false,
        },
        use:{
            trigger:{
                global:"phaseAfter",
            },
            silent:true,
            forced:true,
            content:function (){
                player.phaseUse();
            },
            sub:true,
            popup:false,
        },
    }
}